export const SET_ACTIVE_ATTRACTION_FILTER = 'ATTRACTION/SET_ACTIVE_FILTER';
export const CREATE_ATTRACTION_ORDER = 'ATTRACTION/CREATE_ORDER';
export const CLEAN_ATTRACTION_ORDER_STATUS = 'ATTRACTION/CLEAN_ORDER_STATUS';
export const TOGGLE_ORDER_CREATION_LOADER =
  'ATTRACTION/TOOGLE_ORDER_CREATION_LOADER';

export const GET_ATTRACTIONS = 'ATTRACTIONS/GET_ATTRACTIONS';
export const FETCH_ATTRACTIONS_OFFERS = 'ATTRACTION/FETCH_ATTRACTIONS_OFFERS';
